services:
  # NGINX Proxy Manager:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    pull_policy: always
    restart: unless-stopped
    ports:
      ## These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      ## Add any other Stream port you want to expose
      # - '21:21' # FTP

    ## Uncomment the next line if you uncomment anything in the section
    ## environment:
      ## Uncomment this if you want to change the location of
      ## the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      ## Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt


  ## Uncomment the following lines if you want a dedicated homepage
  ## served thorugh another NGINX (by default on port 82):
  # homepage:
  #   image: cupcakearmy/static:latest
  #   pull_policy: always
  #   restart: unless-stopped
  #   ports:
  #     - 82:80
  #   volumes:
  #     - ./homepage:/srv:ro


## Uncomment the following lines if you want to run the containers
## in a specific Docker Network:
# networks:
#   default:
#     external: false
#     name: services
